# Generated by Django 4.2.11 on 2024-05-13 06:30

from django.db import migrations

def custom_migrate(apps, schema_editor):
    Book2 = apps.get_model('website', 'Book2')
    Books = apps.get_model('website', 'Books')

    for book in Books.objects.all():
        Book2.objects.create(
            title=book.title,
            genre=book.genre,
            price=book.price,
            published_date=book.published_date,
            publisher=book.publisher,
            author=book.author,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_book2'),
    ]

    operations = [
        migrations.RunPython(custom_migrate)
    ]
