# Generated by Django 4.2.11 on 2024-05-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20240513_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book2',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books2', to='website.author'),
        ),
        migrations.AlterField(
            model_name='book2',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books3', related_query_name='books3', to='website.publisher'),
        ),
    ]
