# Generated by Django 4.2.11 on 2024-05-01 07:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('telephone', models.IntegerField(max_length=10)),
                ('address', models.TextField(max_length=255)),
                ('author', models.ManyToManyField(to='website.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('join_date', models.DateField(default=datetime.date(2024, 5, 1))),
                ('popularity_score', models.IntegerField(max_length=3)),
                ('publisher', models.ManyToManyField(to='website.publishers')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('published_date', models.DateField(default=datetime.date(2024, 5, 1))),
                ('author', models.ManyToManyField(to='website.authors')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.publishers')),
            ],
        ),
        migrations.AddField(
            model_name='authors',
            name='followers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.users'),
        ),
    ]
